import {
  Award,
  Boxes,
  BrainCircuit,
  ChartLine,
  Cloud,
  CodeXml,
  Factory,
  FlaskConical,
  Gem,
  Headset,
  Layers,
  Mountain,
  Receipt,
  Shirt,
  ShoppingBag,
  Store,
  Target,
  TreePine,
  Truck,
  Users,
  Warehouse,
  Wheat,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  users: Users,
  layers: Layers,
  headset: Headset,
  target: Target,
  award: Award,
  chart: ChartLine,
  workflow: Workflow,
  cloud: Cloud,
  brain: BrainCircuit,
  receipt: Receipt,
  code: CodeXml,
  factory: Factory,
  mountain: Mountain,
  boxes: Boxes,
  wheat: Wheat,
  store: Store,
  truck: Truck,
  flask: FlaskConical,
  gem: Gem,
  warehouse: Warehouse,
  trees: TreePine,
  shirt: Shirt,
  zap: Zap,
  bag: ShoppingBag,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Cmp = iconMap[name] ?? Layers;
  return <Cmp className={className} aria-hidden="true" />;
}
